// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contact.tracing.proto

package contact_tracing

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	longrunning "google.golang.org/genproto/googleapis/longrunning"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TraceUserLocationsRequest is request to trace a user locations
type TraceUserLocationsRequest struct {
	PhoneNumber          string   `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	SinceDate            string   `protobuf:"bytes,2,opt,name=since_date,json=sinceDate,proto3" json:"since_date,omitempty"`
	Counties             []string `protobuf:"bytes,3,rep,name=counties,proto3" json:"counties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraceUserLocationsRequest) Reset()         { *m = TraceUserLocationsRequest{} }
func (m *TraceUserLocationsRequest) String() string { return proto.CompactTextString(m) }
func (*TraceUserLocationsRequest) ProtoMessage()    {}
func (*TraceUserLocationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ae6e26d4069219a, []int{0}
}

func (m *TraceUserLocationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceUserLocationsRequest.Unmarshal(m, b)
}
func (m *TraceUserLocationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceUserLocationsRequest.Marshal(b, m, deterministic)
}
func (m *TraceUserLocationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceUserLocationsRequest.Merge(m, src)
}
func (m *TraceUserLocationsRequest) XXX_Size() int {
	return xxx_messageInfo_TraceUserLocationsRequest.Size(m)
}
func (m *TraceUserLocationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceUserLocationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TraceUserLocationsRequest proto.InternalMessageInfo

func (m *TraceUserLocationsRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *TraceUserLocationsRequest) GetSinceDate() string {
	if m != nil {
		return m.SinceDate
	}
	return ""
}

func (m *TraceUserLocationsRequest) GetCounties() []string {
	if m != nil {
		return m.Counties
	}
	return nil
}

// TraceUserLocationsRequest is request to trace a user locations
type TraceUsersLocationsRequest struct {
	Counties             []string `protobuf:"bytes,1,rep,name=counties,proto3" json:"counties,omitempty"`
	SinceDate            string   `protobuf:"bytes,2,opt,name=since_date,json=sinceDate,proto3" json:"since_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraceUsersLocationsRequest) Reset()         { *m = TraceUsersLocationsRequest{} }
func (m *TraceUsersLocationsRequest) String() string { return proto.CompactTextString(m) }
func (*TraceUsersLocationsRequest) ProtoMessage()    {}
func (*TraceUsersLocationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ae6e26d4069219a, []int{1}
}

func (m *TraceUsersLocationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceUsersLocationsRequest.Unmarshal(m, b)
}
func (m *TraceUsersLocationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceUsersLocationsRequest.Marshal(b, m, deterministic)
}
func (m *TraceUsersLocationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceUsersLocationsRequest.Merge(m, src)
}
func (m *TraceUsersLocationsRequest) XXX_Size() int {
	return xxx_messageInfo_TraceUsersLocationsRequest.Size(m)
}
func (m *TraceUsersLocationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceUsersLocationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TraceUsersLocationsRequest proto.InternalMessageInfo

func (m *TraceUsersLocationsRequest) GetCounties() []string {
	if m != nil {
		return m.Counties
	}
	return nil
}

func (m *TraceUsersLocationsRequest) GetSinceDate() string {
	if m != nil {
		return m.SinceDate
	}
	return ""
}

// ContactTracingOperation is contains data for contact tracing
type ContactTracingOperation struct {
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	County               string                 `protobuf:"bytes,2,opt,name=county,proto3" json:"county,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Timestamp            int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload              *longrunning.Operation `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ContactTracingOperation) Reset()         { *m = ContactTracingOperation{} }
func (m *ContactTracingOperation) String() string { return proto.CompactTextString(m) }
func (*ContactTracingOperation) ProtoMessage()    {}
func (*ContactTracingOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ae6e26d4069219a, []int{2}
}

func (m *ContactTracingOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactTracingOperation.Unmarshal(m, b)
}
func (m *ContactTracingOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactTracingOperation.Marshal(b, m, deterministic)
}
func (m *ContactTracingOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactTracingOperation.Merge(m, src)
}
func (m *ContactTracingOperation) XXX_Size() int {
	return xxx_messageInfo_ContactTracingOperation.Size(m)
}
func (m *ContactTracingOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactTracingOperation.DiscardUnknown(m)
}

var xxx_messageInfo_ContactTracingOperation proto.InternalMessageInfo

func (m *ContactTracingOperation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ContactTracingOperation) GetCounty() string {
	if m != nil {
		return m.County
	}
	return ""
}

func (m *ContactTracingOperation) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ContactTracingOperation) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ContactTracingOperation) GetPayload() *longrunning.Operation {
	if m != nil {
		return m.Payload
	}
	return nil
}

// ListOperationsRequest is request to get list of contact tracing operations
type ListOperationsRequest struct {
	County               string   `protobuf:"bytes,1,opt,name=county,proto3" json:"county,omitempty"`
	PageToken            int32    `protobuf:"varint,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOperationsRequest) Reset()         { *m = ListOperationsRequest{} }
func (m *ListOperationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListOperationsRequest) ProtoMessage()    {}
func (*ListOperationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ae6e26d4069219a, []int{3}
}

func (m *ListOperationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOperationsRequest.Unmarshal(m, b)
}
func (m *ListOperationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOperationsRequest.Marshal(b, m, deterministic)
}
func (m *ListOperationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOperationsRequest.Merge(m, src)
}
func (m *ListOperationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListOperationsRequest.Size(m)
}
func (m *ListOperationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOperationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOperationsRequest proto.InternalMessageInfo

func (m *ListOperationsRequest) GetCounty() string {
	if m != nil {
		return m.County
	}
	return ""
}

func (m *ListOperationsRequest) GetPageToken() int32 {
	if m != nil {
		return m.PageToken
	}
	return 0
}

func (m *ListOperationsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// ListOperationsResponse is response containing collection contact tracing operation
type ListOperationsResponse struct {
	Operations           []*ContactTracingOperation `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	NextPageToken        int32                      `protobuf:"varint,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ListOperationsResponse) Reset()         { *m = ListOperationsResponse{} }
func (m *ListOperationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListOperationsResponse) ProtoMessage()    {}
func (*ListOperationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ae6e26d4069219a, []int{4}
}

func (m *ListOperationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOperationsResponse.Unmarshal(m, b)
}
func (m *ListOperationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOperationsResponse.Marshal(b, m, deterministic)
}
func (m *ListOperationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOperationsResponse.Merge(m, src)
}
func (m *ListOperationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListOperationsResponse.Size(m)
}
func (m *ListOperationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOperationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOperationsResponse proto.InternalMessageInfo

func (m *ListOperationsResponse) GetOperations() []*ContactTracingOperation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func (m *ListOperationsResponse) GetNextPageToken() int32 {
	if m != nil {
		return m.NextPageToken
	}
	return 0
}

// ContactTracingResponse contains the ID of the contact tracing operation
type ContactTracingResponse struct {
	OperationId          int64    `protobuf:"varint,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactTracingResponse) Reset()         { *m = ContactTracingResponse{} }
func (m *ContactTracingResponse) String() string { return proto.CompactTextString(m) }
func (*ContactTracingResponse) ProtoMessage()    {}
func (*ContactTracingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3ae6e26d4069219a, []int{5}
}

func (m *ContactTracingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactTracingResponse.Unmarshal(m, b)
}
func (m *ContactTracingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactTracingResponse.Marshal(b, m, deterministic)
}
func (m *ContactTracingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactTracingResponse.Merge(m, src)
}
func (m *ContactTracingResponse) XXX_Size() int {
	return xxx_messageInfo_ContactTracingResponse.Size(m)
}
func (m *ContactTracingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactTracingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContactTracingResponse proto.InternalMessageInfo

func (m *ContactTracingResponse) GetOperationId() int64 {
	if m != nil {
		return m.OperationId
	}
	return 0
}

func init() {
	proto.RegisterType((*TraceUserLocationsRequest)(nil), "covitrace.TraceUserLocationsRequest")
	proto.RegisterType((*TraceUsersLocationsRequest)(nil), "covitrace.TraceUsersLocationsRequest")
	proto.RegisterType((*ContactTracingOperation)(nil), "covitrace.ContactTracingOperation")
	proto.RegisterType((*ListOperationsRequest)(nil), "covitrace.ListOperationsRequest")
	proto.RegisterType((*ListOperationsResponse)(nil), "covitrace.ListOperationsResponse")
	proto.RegisterType((*ContactTracingResponse)(nil), "covitrace.ContactTracingResponse")
}

func init() { proto.RegisterFile("contact.tracing.proto", fileDescriptor_3ae6e26d4069219a) }

var fileDescriptor_3ae6e26d4069219a = []byte{
	// 577 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0x26, 0xad, 0x5d, 0x37, 0xa7, 0x6b, 0x17, 0x67, 0xd9, 0x1a, 0xe3, 0x56, 0xd2, 0xf1, 0xaf,
	0x88, 0x4d, 0xb0, 0x5e, 0x08, 0x7a, 0xb7, 0x7a, 0x23, 0x2c, 0x2a, 0xb1, 0x22, 0x78, 0x13, 0x66,
	0x93, 0x21, 0x0e, 0xdb, 0xce, 0xc4, 0xcc, 0x74, 0xd7, 0xae, 0x88, 0x20, 0x5e, 0x7a, 0xe7, 0x95,
	0xaf, 0xe2, 0x6b, 0xf8, 0x0a, 0x3e, 0x88, 0x64, 0xd2, 0xa6, 0x89, 0x4d, 0x11, 0xbc, 0x0a, 0xf3,
	0xcd, 0x39, 0xe7, 0xfb, 0xce, 0x39, 0x5f, 0x06, 0xf6, 0x43, 0xc1, 0x15, 0x09, 0x95, 0xab, 0x52,
	0x12, 0x32, 0x1e, 0xbb, 0x49, 0x2a, 0x94, 0x40, 0x66, 0x28, 0x4e, 0x59, 0x06, 0x51, 0xfb, 0x46,
	0x2c, 0x44, 0x3c, 0xa1, 0xde, 0x44, 0xf0, 0x38, 0x9d, 0x71, 0xce, 0x78, 0xec, 0x89, 0x84, 0xa6,
	0x44, 0x31, 0xc1, 0x65, 0x1e, 0x6f, 0x1f, 0x2c, 0x82, 0x48, 0xc2, 0x3c, 0xc2, 0xb9, 0x50, 0x95,
	0xdb, 0x7b, 0xfa, 0x13, 0x0e, 0x63, 0xca, 0x87, 0xf2, 0x8c, 0xc4, 0x31, 0x4d, 0x3d, 0x91, 0xe8,
	0x88, 0xf5, 0x68, 0x3c, 0x87, 0xab, 0xe3, 0x8c, 0xf9, 0xb5, 0xa4, 0xe9, 0x91, 0x08, 0xf3, 0x3b,
	0x9f, 0xbe, 0x9f, 0x51, 0xa9, 0x50, 0x1f, 0x76, 0x92, 0x77, 0x82, 0xd3, 0x80, 0xcf, 0xa6, 0xc7,
	0x34, 0xb5, 0x0c, 0xc7, 0x18, 0x98, 0x7e, 0x5b, 0x63, 0xcf, 0x35, 0x84, 0x7a, 0x00, 0x92, 0xf1,
	0x90, 0x06, 0x11, 0x51, 0xd4, 0x6a, 0xe8, 0x00, 0x53, 0x23, 0x4f, 0x89, 0xa2, 0xc8, 0x86, 0xed,
	0x50, 0xcc, 0xb8, 0x62, 0x54, 0x5a, 0x4d, 0xa7, 0x39, 0x30, 0xfd, 0xe2, 0x8c, 0xdf, 0x80, 0x5d,
	0x50, 0xcb, 0x35, 0xee, 0x72, 0xa6, 0x51, 0xcd, 0xfc, 0x07, 0x29, 0xfe, 0x69, 0xc0, 0x95, 0x27,
	0xf9, 0xa4, 0xc7, 0xf9, 0xa0, 0x5f, 0x2c, 0x47, 0x88, 0x3a, 0xd0, 0x60, 0x91, 0x6e, 0xa4, 0xe9,
	0x37, 0x58, 0x84, 0xba, 0xb0, 0xa5, 0xcb, 0xce, 0x17, 0x65, 0x16, 0x27, 0xe4, 0x40, 0x3b, 0xa2,
	0x32, 0x4c, 0x99, 0x9e, 0x9c, 0xd5, 0xcc, 0x3b, 0x2f, 0x41, 0xe8, 0x00, 0x4c, 0xc5, 0xa6, 0x54,
	0x2a, 0x32, 0x4d, 0xac, 0x0b, 0xba, 0xe0, 0x0a, 0x40, 0x0f, 0xe1, 0x62, 0x42, 0xe6, 0x13, 0x41,
	0x22, 0xab, 0xe5, 0x18, 0x83, 0xf6, 0xa8, 0xe7, 0xe6, 0x5b, 0x73, 0x4b, 0xab, 0x75, 0x0b, 0x5d,
	0xfe, 0x32, 0x1a, 0x9f, 0xc0, 0xfe, 0x11, 0x93, 0xaa, 0xb8, 0x29, 0x06, 0xb2, 0x52, 0x6a, 0x54,
	0x94, 0xf6, 0x00, 0x12, 0x12, 0xd3, 0x40, 0x89, 0x13, 0xca, 0x75, 0x17, 0x2d, 0xdf, 0xcc, 0x90,
	0x71, 0x06, 0xa0, 0x6b, 0xa0, 0x0f, 0x81, 0x64, 0xe7, 0x54, 0xb7, 0xd1, 0xf2, 0xb7, 0x33, 0xe0,
	0x15, 0x3b, 0xa7, 0xf8, 0xab, 0x01, 0xdd, 0xbf, 0xd9, 0x64, 0x22, 0xb8, 0xa4, 0xe8, 0x10, 0x60,
	0x65, 0x3c, 0xbd, 0x81, 0xf6, 0x08, 0xbb, 0x85, 0x53, 0xdd, 0x0d, 0x03, 0xf6, 0x4b, 0x59, 0xe8,
	0x36, 0xec, 0x72, 0xfa, 0x41, 0x05, 0x6b, 0xfa, 0x2e, 0x65, 0xf0, 0xcb, 0xa5, 0x46, 0xfc, 0x18,
	0xba, 0xd5, 0x72, 0x85, 0x8a, 0x3e, 0xec, 0x14, 0xf5, 0x82, 0x62, 0x71, 0xed, 0x02, 0x7b, 0x16,
	0x8d, 0x7e, 0x34, 0xa1, 0x53, 0xcd, 0x46, 0xdf, 0x0c, 0x40, 0xeb, 0xae, 0x46, 0x37, 0x4b, 0xf2,
	0x37, 0x9a, 0xde, 0xee, 0x6f, 0x6c, 0x72, 0xa9, 0x0a, 0x0f, 0xbf, 0xfc, 0xfa, 0xfd, 0xbd, 0x71,
	0x07, 0x63, 0xfd, 0x0b, 0x9e, 0xde, 0xf7, 0x74, 0xb4, 0x37, 0xcb, 0x8c, 0xec, 0x7d, 0x2c, 0xff,
	0x32, 0x9f, 0x1e, 0x19, 0x77, 0xd1, 0x67, 0xd8, 0xab, 0x31, 0x3a, 0xba, 0x55, 0x27, 0x47, 0xfe,
	0x8f, 0x9e, 0xeb, 0x5a, 0x8f, 0x85, 0xf7, 0x6a, 0xf4, 0x64, 0x02, 0xce, 0xa0, 0x53, 0xdd, 0x32,
	0x72, 0x4a, 0x45, 0x6b, 0xed, 0x56, 0xa1, 0xad, 0xb7, 0x08, 0x76, 0x34, 0xad, 0x8d, 0xac, 0x2a,
	0xed, 0xca, 0x00, 0x87, 0x97, 0xdf, 0xee, 0x2e, 0x9e, 0xbc, 0x60, 0xf1, 0xe4, 0x1d, 0x6f, 0xe9,
	0x77, 0xe7, 0xc1, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x7b, 0xb0, 0xd3, 0x0c, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContactTracingClient is the client API for ContactTracing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactTracingClient interface {
	// Traces user locations and matching corresponding contact points
	TraceUserLocations(ctx context.Context, in *TraceUserLocationsRequest, opts ...grpc.CallOption) (*ContactTracingResponse, error)
	// Traces user locations and matching corresponding contact points
	TraceUsersLocations(ctx context.Context, in *TraceUsersLocationsRequest, opts ...grpc.CallOption) (*ContactTracingResponse, error)
	// Fetches contact tracing operations
	ListOperations(ctx context.Context, in *ListOperationsRequest, opts ...grpc.CallOption) (*ListOperationsResponse, error)
}

type contactTracingClient struct {
	cc *grpc.ClientConn
}

func NewContactTracingClient(cc *grpc.ClientConn) ContactTracingClient {
	return &contactTracingClient{cc}
}

func (c *contactTracingClient) TraceUserLocations(ctx context.Context, in *TraceUserLocationsRequest, opts ...grpc.CallOption) (*ContactTracingResponse, error) {
	out := new(ContactTracingResponse)
	err := c.cc.Invoke(ctx, "/covitrace.ContactTracing/TraceUserLocations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactTracingClient) TraceUsersLocations(ctx context.Context, in *TraceUsersLocationsRequest, opts ...grpc.CallOption) (*ContactTracingResponse, error) {
	out := new(ContactTracingResponse)
	err := c.cc.Invoke(ctx, "/covitrace.ContactTracing/TraceUsersLocations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactTracingClient) ListOperations(ctx context.Context, in *ListOperationsRequest, opts ...grpc.CallOption) (*ListOperationsResponse, error) {
	out := new(ListOperationsResponse)
	err := c.cc.Invoke(ctx, "/covitrace.ContactTracing/ListOperations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactTracingServer is the server API for ContactTracing service.
type ContactTracingServer interface {
	// Traces user locations and matching corresponding contact points
	TraceUserLocations(context.Context, *TraceUserLocationsRequest) (*ContactTracingResponse, error)
	// Traces user locations and matching corresponding contact points
	TraceUsersLocations(context.Context, *TraceUsersLocationsRequest) (*ContactTracingResponse, error)
	// Fetches contact tracing operations
	ListOperations(context.Context, *ListOperationsRequest) (*ListOperationsResponse, error)
}

func RegisterContactTracingServer(s *grpc.Server, srv ContactTracingServer) {
	s.RegisterService(&_ContactTracing_serviceDesc, srv)
}

func _ContactTracing_TraceUserLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceUserLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactTracingServer).TraceUserLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/covitrace.ContactTracing/TraceUserLocations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactTracingServer).TraceUserLocations(ctx, req.(*TraceUserLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactTracing_TraceUsersLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TraceUsersLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactTracingServer).TraceUsersLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/covitrace.ContactTracing/TraceUsersLocations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactTracingServer).TraceUsersLocations(ctx, req.(*TraceUsersLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactTracing_ListOperations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactTracingServer).ListOperations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/covitrace.ContactTracing/ListOperations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactTracingServer).ListOperations(ctx, req.(*ListOperationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactTracing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "covitrace.ContactTracing",
	HandlerType: (*ContactTracingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TraceUserLocations",
			Handler:    _ContactTracing_TraceUserLocations_Handler,
		},
		{
			MethodName: "TraceUsersLocations",
			Handler:    _ContactTracing_TraceUsersLocations_Handler,
		},
		{
			MethodName: "ListOperations",
			Handler:    _ContactTracing_ListOperations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contact.tracing.proto",
}
