apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandemic-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pandemic-api-gateway
  template:
    metadata:
      labels:
        app: pandemic-api-gateway
    spec:
      containers:
      - name: pandemic-api-gateway
        image: gidyon/pandemic-api:latest
        args: ["--cors", "--services-file", "/app/configs/gateway.yml", "--port", "443"]
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        readinessProbe: # Checks that the container is started
          httpGet:
            path: /readyq
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe: # Checks that the container is running
          httpGet:
            path: /liveq
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        volumeMounts:
          - name: app-tls
            mountPath: /app/secrets/keys/
            readOnly: true
          - name: gateway-config
            mountPath: /app/configs/
            readOnly: true
          - name: mysql-creds
            mountPath: /app/secrets/mysql/
            readOnly: true
          - name: messaging-tls
            mountPath: /app/secrets/keys/messaging
            readOnly: true
          - name: tracing-tls
            mountPath: /app/secrets/keys/tracing
            readOnly: true
          - name: location-tls
            mountPath: /app/secrets/keys/location
            readOnly: true
          - name: restful-tls
            mountPath: /app/secrets/keys/restful
            readOnly: true
      volumes:
      - name: app-tls
        secret:
          secretName: gateway-tls-v1
      - name: gateway-config
        configMap:
          name: gateway-v4
      - name: mysql-creds
        secret:
          secretName: mysql-credentials
      - name: tracing-tls
        secret:
          secretName: tracing-tls-v1
      - name: messaging-tls
        secret:
          secretName: messaging-tls-v1
      - name: location-tls
        secret:
          secretName: location-tls-v1
      - name: restful-tls
        secret:
          secretName: restful-tls-v1

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "pandemic-api-gateway-hpa"
  labels:
    app: "pandemic-api-gateway"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "pandemic-api-gateway"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: pandemic-api-gateway
spec:
  type: NodePort
  selector:
    app: pandemic-api-gateway
  ports:
  - port: 443
    name: https
    targetPort: https
    protocol: TCP
    nodePort: 30783
  - port: 80
    name: http
    targetPort: https
    protocol: TCP
    nodePort: 30780