apiVersion: v1
kind: Service
metadata:
  name: fightcovid19-np
  labels:
    app: fightcovid19
spec:
  type: NodePort
  selector:
    app: fightcovid19
  ports:
  - port: 443
    name: https
    targetPort: https
    protocol: TCP
    nodePort: 30783
  - port: 80
    name: http
    targetPort: https
    protocol: TCP
    nodePort: 30780
