// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"

	messaging "github.com/gidyon/pandemic-api/pkg/api/messaging"

	mock "github.com/stretchr/testify/mock"
)

// MessagingClientMock is an autogenerated mock type for the MessagingClientMock type
type MessagingClientMock struct {
	mock.Mock
}

// AlertContacts provides a mock function with given fields: ctx, opts
func (_m *MessagingClientMock) AlertContacts(ctx context.Context, opts ...grpc.CallOption) (messaging.Messaging_AlertContactsClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 messaging.Messaging_AlertContactsClient
	if rf, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) messaging.Messaging_AlertContactsClient); ok {
		r0 = rf(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(messaging.Messaging_AlertContactsClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BroadCastMessage provides a mock function with given fields: ctx, in, opts
func (_m *MessagingClientMock) BroadCastMessage(ctx context.Context, in *messaging.BroadCastMessageRequest, opts ...grpc.CallOption) (*messaging.BroadCastMessageResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *messaging.BroadCastMessageResponse
	if rf, ok := ret.Get(0).(func(context.Context, *messaging.BroadCastMessageRequest, ...grpc.CallOption) *messaging.BroadCastMessageResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messaging.BroadCastMessageResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *messaging.BroadCastMessageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNewMessagesCount provides a mock function with given fields: ctx, in, opts
func (_m *MessagingClientMock) GetNewMessagesCount(ctx context.Context, in *messaging.MessageRequest, opts ...grpc.CallOption) (*messaging.NewMessagesCount, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *messaging.NewMessagesCount
	if rf, ok := ret.Get(0).(func(context.Context, *messaging.MessageRequest, ...grpc.CallOption) *messaging.NewMessagesCount); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messaging.NewMessagesCount)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *messaging.MessageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListMessages provides a mock function with given fields: ctx, in, opts
func (_m *MessagingClientMock) ListMessages(ctx context.Context, in *messaging.ListMessagesRequest, opts ...grpc.CallOption) (*messaging.Messages, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *messaging.Messages
	if rf, ok := ret.Get(0).(func(context.Context, *messaging.ListMessagesRequest, ...grpc.CallOption) *messaging.Messages); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messaging.Messages)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *messaging.ListMessagesRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadAll provides a mock function with given fields: ctx, in, opts
func (_m *MessagingClientMock) ReadAll(ctx context.Context, in *messaging.MessageRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *empty.Empty
	if rf, ok := ret.Get(0).(func(context.Context, *messaging.MessageRequest, ...grpc.CallOption) *empty.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*empty.Empty)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *messaging.MessageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SendMessage provides a mock function with given fields: ctx, in, opts
func (_m *MessagingClientMock) SendMessage(ctx context.Context, in *messaging.Message, opts ...grpc.CallOption) (*messaging.SendMessageResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *messaging.SendMessageResponse
	if rf, ok := ret.Get(0).(func(context.Context, *messaging.Message, ...grpc.CallOption) *messaging.SendMessageResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*messaging.SendMessageResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *messaging.Message, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
