apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: pandemic-api
spec:
  selector:
    app: mysql
  ports:
  - port: 80
    targetPort: mysql
    protocol: TCP
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: pandemic-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-database
        image: mysql:8.0.18
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-creds
              key: schema
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: database
          mountPath: "/var/lib/mysql"
      volumes:
      - name: database
        persistentVolumeClaim:
         claimName: mysql-pvc
