apiVersion: v1
kind: Service
metadata:
  name: mysql-np
  labels:
    app: fightcovid19
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - port: 80
    targetPort: mysql
    protocol: TCP
    name: http
    nodePort: 30800
