apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandemic-api-location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pandemic-api-location
  template:
    metadata:
      labels:
        app: pandemic-api-location
    spec:
      containers:
      - name: pandemic-api-location
        image: gidyon/pandemic-api-location:v0.3
        args: ["--config-file", "/app/configs/config.yml"]
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        readinessProbe: # Checks that the container is started
          httpGet:
            path: /api/v1/locations/readyq/
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe: # Checks that the container is running
          httpGet:
            path: /api/v1/locations/liveq/
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        volumeMounts:
          - name: app-tls
            mountPath: /app/secrets/keys/
            readOnly: true
          - name: app-config
            mountPath: /app/configs/
            readOnly: true
          - name: mysql-creds
            mountPath: /app/secrets/mysql/
            readOnly: true
      volumes:
      - name: app-tls
        secret:
          secretName: location-tls-v1
      - name: app-config
        configMap:
          name: location-v2
      - name: mysql-creds
        secret:
          secretName: mysql-credentials

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "pandemic-api-location-hpa"
  labels:
    app: "pandemic-api-location"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "pandemic-api-location"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: messaging
  labels:
    app: pandemic-api-location
spec:
  clusterIP: None
  selector:
    app: pandemic-api-location
  ports:
  - port: 443
    name: https
    targetPort: https
    protocol: TCP
  - port: 80
    name: http
    targetPort: https
    protocol: TCP