apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandemic-api-messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pandemic-api-messaging
  template:
    metadata:
      labels:
        app: pandemic-api-messaging
    spec:
      containers:
      - name: pandemic-api-messaging
        image: gidyon/pandemic-api-messaging:v0.8
        args: ["--config-file", "/app/configs/config.yml"]
        imagePullPolicy: Always
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        readinessProbe: # Checks that the container is started
          httpGet:
            path: /api/v1/messaging/readyq/
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe: # Checks that the container is running
          httpGet:
            path: /api/v1/messaging/liveq/
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        env:
        - name: FCM_SERVER_KEY
          valueFrom:
            secretKeyRef:
              name: fcm-creds
              key: server-key
        volumeMounts:
          - name: app-tls
            mountPath: /app/secrets/keys/
            readOnly: true
          - name: app-config
            mountPath: /app/configs/
            readOnly: true
          - name: mysql-creds
            mountPath: /app/secrets/mysql/
            readOnly: true
      volumes:
      - name: app-tls
        secret:
          secretName: messaging-tls-v1
      - name: app-config
        configMap:
          name: messaging-v2
      - name: mysql-creds
        secret:
          secretName: mysql-credentials

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "pandemic-api-messaging-hpa"
  labels:
    app: "pandemic-api-messaging"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "pandemic-api-messaging"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: messaging
  labels:
    app: pandemic-api-messaging
spec:
  clusterIP: None
  selector:
    app: pandemic-api-messaging
  ports:
  - port: 443
    name: https
    targetPort: https
    protocol: TCP
  - port: 80
    name: http
    targetPort: https
    protocol: TCP