apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandemic-api-tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pandemic-api-tracing
  template:
    metadata:
      labels:
        app: pandemic-api-tracing
    spec:
      containers:
      - name: pandemic-api-tracing
        image: gidyon/pandemic-api-tracing:v0.6
        args: ["--config-file", "/app/configs/config.yml"]
        imagePullPolicy: Always
        ports:
        - containerPort: 5600
          name: https
          protocol: TCP
        readinessProbe: # Checks that the container is started
          httpGet:
            path: /api/v1/trace/readyq/
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe: # Checks that the container is running
          httpGet:
            path: /api/v1/trace/liveq/
            scheme: HTTPS
            port: 443
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        volumeMounts:
          - name: app-tls
            mountPath: /app/secrets/keys/
            readOnly: true
          - name: messaging-tls
            mountPath: /app/secrets/keys/messaging
            readOnly: true
          - name: app-config
            mountPath: /app/configs/
            readOnly: true
          - name: mysql-creds
            mountPath: /app/secrets/mysql/
            readOnly: true
      volumes:
      - name: app-tls
        secret:
          secretName: tracing-tls-v1
      - name: messaging-tls
        secret:
          secretName: messaging-tls-v1
      - name: app-config
        configMap:
          name: tracing-v2
      - name: mysql-creds
        secret:
          secretName: mysql-credentials

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "pandemic-api-tracing-hpa"
  labels:
    app: "pandemic-api-tracing"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "pandemic-api-tracing"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: tracing
  labels:
    app: pandemic-api-tracing
spec:
  clusterIP: None
  selector:
    app: pandemic-api-tracing
  ports:
  - port: 443
    name: https
    targetPort: https
    protocol: TCP
  - port: 80
    name: http
    targetPort: https
    protocol: TCP